name: LunarSMP
version: '${project.version}'
main: light.breeze.LunarSMP
api-version: 1.20
authors: [ guhw ]
description: lol
commands:
  lunarsmp:
    description: shows ascii art
    usage: /<command>
    permission: minecraft.command.help

  customgive:
    description: gives custom items
    usage: /<command>
    permission: minecraft.command.give

  echotarget:
    description: sets echo target
    usage: /<command>
    permission: minecraft.command.help