name: LunarSMP
version: '${project.version}'
main: light.breeze.LunarSMP
api-version: 1.20
authors: [ guhw ]
depend: [PlaceholderAPI]
description: lol
commands:
  lunar_smp:
    description: shows ascii art
    usage: /<command>
    permission: minecraft.command.help

  custom_give:
    description: gives custom items
    aliases: [ customgive ]
    usage: /<command>
    permission: minecraft.command.give

  echo_target:
    description: sets echo target
    aliases: [ echotarget ]
    usage: /<command>
    permission: minecraft.command.help

  dev:
    description: dev command
    usage: /<command>
    permission: minecraft.command.give

  tpa:
    description: requests to TP to someone
    aliases: [ tpa, tpato, tpahere, tpaccept, tpacancel, tpcancel, tpaaccept, tpdecline, tpadecline ]
    usage: /tpa <player>
    permission: minecraft.command.help

  mana:
    description: gets mana
    aliases: [ get_mana ]
    usage: /<command>
    permission: minecraft.command.help

  open_brewer:
    description: brew
    aliases: [ brewer,custom_brew,open_custom_brewer ]
    usage: /<command>
    permission: minecraft.command.help