name: LunarSMP
version: '${project.version}'
main: light.breeze.LunarSMP
api-version: 1.20
authors: [ guhw ]
description: lol
commands:
  lunarsmp:
    description: shows ascii art
    usage: /<command>
    permission: minecraft.command.help

  customgive:
    description: gives custom items
    usage: /<command>
    permission: minecraft.command.give

  echotarget:
    description: sets echo target
    usage: /<command>
    permission: minecraft.command.help

  dev:
    description: dev command
    usage: /<command>
    permission: minecraft.command.give

  tpa:
    description: requests to TP to someone
    aliases: [tpa, tpato, tpahere, tpaccept, tpacancel, tpcancel, tpaaccept, tpdecline, tpadecline]
    usage: /tpa <player>
    permission: minecraft.command.help

  mana:
    description: gets mana
    aliases: [getmana]
    usage: /<command>
    permission: minecraft.command.help

  openbrewer:
    description: brew
    aliases: [brewer,custombrew,opencustombrewer]
    usage: /<command>
    permission: minecraft.command.help