name: LunarRevamped
version: '1.0.0'
main: light.breeze.lunarsmp.LunarRevamped
api-version: '1.20'
softdepend: [PlaceholderAPI]
description: Lunar Revamped
commands:
  lunar_give:
    description: Gives you an item
    usage: /fuck around and find out/
    permission: minecraft.command.give
  tpa:
    description: TPA
    usage: /tpa <plr>
    permission: minecraft.command.help
    aliases: ["tpa", "tpaccept", "tpaaccept", "tpadecline", "tpato", "tpahere", "tpano", "tpayes",]